### ISSUE TITLE
Reduce size of the repo

### ISSUE THREAD

**Issue by dalonsoa** [ImperialCollegeLondon/ReCoDe_Euler_Maruyama#4]
When cloning the repository, this seems to be ~35 Mb in size, which is enormous. That's not a fundamental problem, but it is certainly annoying and unnecessary for the most part. Part of this size is explained by notebooks 3 and 4, which contain a lot of BIG figures, but another part is due to the commit history which might have copies of these notebooks as they were being developed. 

I would suggest:
- Review the notebooks to try to reduce the figures size - and therefore the overall notebook size
- Use https://rtyley.github.io/bfg-repo-cleaner/ to remove any old file (just make sure you don't remove the latest versions!)

**Comment by NonoMalpi** [comment]
Hi @dalonsoa, I have followed your recommendations. Now notebooks 3 and 4 have reduced size compared to old versions. I have also applied the `bfg` command to remove old files from commit history. However I have tried to clone the repository after the changes and it seems to be ~35 Mb in size again. Any thoughts on what is happenning? Many thanks!
